name: sudoku
channels:
  - anaconda
  - defaults
dependencies:
  - pip=20.1.1=py36_1
  - cython=0.28.2=py36h1de35cc_0
  - jupyter=1.0.0=py36_7
  - matplotlib=2.1.1=py36h2fb3e9e_0
  - nb_conda=2.2.1=py36_0
  - pandas=1.0.5=py36h959d312_0
  - pydot=1.2.4=py36_0
  - pydotplus=2.0.2=py36_1
  - pomegranate=0.9.0=py36h1d22016_0
  - scikit-learn=0.23.1=py36h603561c_0
  - scipy=1.5.0=py36h912ce22_0
  - tqdm=4.19.4=py36he502594_0
  - pip:
    - pygame==1.9.6
    - z3-solver==4.8.8.0

